# [Docker](https://docs.docker.com/):
# - `docker-compose up`.
# - `docker-compose down`.

# [podman](https://podman.io/) - [podman-compose](https://github.com/containers/podman-compose):
# - `podman-compose up`.
# - `podman-compose down.

services:
  dbcache:
    image: redis:7.0.8-alpine
    container_name: Redis
    restart: on-failure
    privileged: true
    ports:
      - '6379:6379'
    volumes:
      - ../databases/redis:/var/lib/postgresql/data